export const APP_COLORS = {
  BACKGROUND_COLOR: '#f8f9ff',
  TEXT_COLOR: '#03050F',
  TEXT_COLOR_SECONDARY: '#141938',
  TEXT_COLOR_MUTED: '#0A051E',
  BACKGROUND_COLOR_SECONDARY: '#fafbff',
  CARD_BACKGROUND_COLOR: '#fff',
  WHITE: '#fff',
  BADGE_GRADIENT: ['#00F4E2', '#00FF7F'],
};
